
services:

  # frontend

  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: workload_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres123@db:5432/workload_db
      SECRET_KEY: your_secret_key #อย่าลืมปรับเป็นคีย์ที่ปลอดภัยใน production
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network


  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: workload_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: workload_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
